### ISSUE TITLE
Express not catch home route

### ISSUE THREAD

**Issue by abaddonGIT** [atulmy/universal-react#1]
Hi. This app.get('*', (request, response) ... not works then i load home page http://localhost:3000/ and server rendering not work this page. How fix this?

**Comment by atulmy** [comment]
Follow these steps:
- Clone repo `git clone git@github.com:atulmy/universal-react.git universal-react`
- Install NPM modules `cd universal-react` and `npm install`
- Run `npm run start`

And make sure you are running latest version of Node (Eg: `v8.9.1`)

If you are still facing issues, you can paste the error logs here for better troubleshooting.

**Comment by abaddonGIT** [comment]
Sorry i don't understand I do not understand what happens, when i reinstall all work perfectly. Thanks for your help)
